micromdm/nanomdm

docs/operations-guide.md

Probably not meant to be in the example?

Remove command output from example

---

storage/mysql/schema.sql

Was having problems running the schema.sql file in MySQL 5.7.32. It was blowing up because of the trailing commas.
Did some research on whether trailing commas are allowed in `CREATE TABLE`. The results didn't seem conclusive. Some RDBMS implementations deem it harmless and won't error on it. 
Wanted to check the SQL language spec next but since this file has some statement without trailing commas, I thought it's probably not intentional and it's easier to just remove it.

Remove trailing commas from CREATE TABLE statements

---

storage/mysql/schema.00005.sql
storage/mysql/schema.sql

Hello!
When handling the command result response for InstalledApplicationList, nanomdm issues the following plea:
```
level=info handler=checkin-command msg=command report results err=storing command report: Error 1406: Data too long for column 'result' at row 1
```
The InstalledApplicationList response for my current device - with only base Apple apps - is 117,465 characters of base64-endcoded text. `TEXT` support 65,525 characters; `MEDIUMTEXT`, 16,777,215 (this corresponds to ~16.78 mb: "L + 3 bytes, where L < 2^24" -  https://dev.mysql.com/doc/refman/8.0/en/storage-requirements.html#data-types-storage-reqs-strings)
This works with current nanomdm release (in as much as I migrated with `schema.00005.sql` and everything continued to work/`InstalledApplicationList` started working). …

Accomodate large command results

---

cmd/nanomdm/main.go
docs/operations-guide.md
mdm/checkin.go
service/certauth/service.go
service/dump/dump.go
service/microwebhook/service.go
service/multi/multi.go
service/nanomdm/dm.go
service/nanomdm/service.go
service/request.go
service/service.go

Implements Declarative Management HTTP hand-off. That is — it extract the declarative management "endpoint" key and data and dispatch to another, real, HTTP server. Use the `-dm` switch and the `Endpoint` key will be appended to that URL. The enrollment ID is also passed along in a header. See the modified [Operations Guide](https://github.com/micromdm/nanomdm/blob/main/docs/operations-guide.md) in this PR for more docs.

Declarative Management

---

tools/cmdr.py

```
usage: cmdr.py ScheduleOSUpdate [-h] [--version VERSION] [--key KEY]
[--deferrals DEFERRALS] [--priority PRIORITY]
action
positional arguments:
action                InstallAction (ex. InstallASAP, InstallLater, etc.)
optional arguments:
-h, --help            show this help message and exit
--version VERSION     ProductVersion (ex. 12.1, 12.2.1, etc.)
--key KEY             ProductKey (ex. MSU_UPDATE_21E5227a_patch_12.3, etc.)
--deferrals DEFERRALS
MaxUserDeferrals (ex. 3, 30, etc.)
--priority PRIORITY   Priority (ex. Low, High.)
```
Example
```
% ./cmdr.py ScheduleOSUpdate InstallASAP --version 12.1 --deferrals 3
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict> …
```

add support for ScheduleOSUpdate to cmdr.py

---

docs/openapi.yaml
http/api.go

Attempt to account for API errors on both the push and enqueue API endpoints. This allows us to give an HTTP status (200, 207, or 500) which roughly correspond to (all succeeded, some failed, all failed).
Resolves #27. Looking for @w0de's input specifically. :)

Account for errors to give appropriate HTTP status

---

http/api.go

- Split out the in-any-order certificate/private-key PEM parsing to its own function.
- Add HTTP status for errors.
- Add a `tls.X509KeyPair()` sanity check.

Simplify StorePushCertHandler

---

tools/cmdr.py

```
% ./cmdr.py Settings --allowbst
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
<key>Command</key>
<dict>
<key>RequestType</key>
<string>Settings</string>
<key>Settings</key>
<array>
<dict>
<key>Item</key>
<string>MDMOptions</string>
<key>MDMOptions</key>
<dict>
<key>BootstrapTokenAllowed</key>
<true/>
</dict>
</dict>
</array>
</dict>
<key>CommandUUID</key>
<string>95e2fb3d-e599-4bf3-ab46-5453265f366e</string>
</dict>
</plist>
```

add support for Settings command

---

docs/quickstart.md

The free tier of ngrok disallows 2 simultaneous agents running. To solve, specify two tunnels in the config file for the one agent to run. Hat tip to: https://www.wesleyabbey.io/post/ngrok-multiple-tunnels

Update quickstart instructions for two tunnels

---

cmd/cli/cli.go
docs/operations-guide.md
storage/mysql/mysql.go
storage/mysql/queue.go
storage/mysql/queue_test.go

From the changes to the operations guide:
> This option turns on the command and response deleter. When enabled (with `delete=1`) command responses, queued commands, and commands themeselves will be deleted from the database after enrollments have responded to a command.
This implements the feature discussed in #43 for the `mysql` storage backend.

Optionally delete commands in mysql storage backend

---

cmd/nano2nano/main.go
cmd/nanomdm/main.go
log/stdlogfmt/stdlog.go

Optionize `stdlogfmt` package/New, add filename and line logging, use timestamp format.
Output looks like:
```
ts=2022-07-21T08:41:40-07:00 level=info msg=storage setup storage=pgsql caller=cli.go:60
ts=2022-07-21T08:41:40-07:00 level=info msg=storage setup storage=mysql caller=cli.go:60
ts=2022-07-21T08:41:40-07:00 level=info msg=storage setup storage=file caller=cli.go:60
ts=2022-07-21T08:41:40-07:00 level=info msg=storage setup storage=multi-storage count=3 caller=cli.go:93
ts=2022-07-21T08:41:40-07:00 level=debug msg=declarative management setup url=http://127.0.0.1:5000/ caller=main.go:102
ts=2022-07-21T08:41:40-07:00 level=info service=certauth msg=allowing retroactive associations caller=certauth.go:95
ts=2022-07-21T08:41:40-07:00 level=info msg=starting server listen=:9000 …
```

stdlogfmt (default logger) changes

---

http/mdm/mdm.go
mdm/checkin.go
mdm/command.go
mdm/mdm.go

This is useful to debug errors that occur because of bad plists sent by
clients. Usually in this case, one receives a not-very-useful error such
as `HTTP status 400 (Bad Request): <opaque error>`.
1. Patch `mdmb` so that it sends bad checkins
```patch
diff --git a/internal/device/mdm.go b/internal/device/mdm.go
index 33a4c50..cda3d69 100644
--- a/internal/device/mdm.go
+++ b/internal/device/mdm.go
@@ -185,10 +185,7 @@ func (c *MDMClient) connect(client *http.Client, connReq interface{}) error {
return errors.New("device not enrolled")
}
-       plistBytes, err := plist.Marshal(connReq)
-       if err != nil {
-               return err
-       }
+       plistBytes := []byte("aoeuaoeuaoeu")
```
2. Run
```
$ mdmb -uuids $uuid devices-connect
```
3. Observe more verbose NanoMDM log:
``` …
```

Add Logging for plist parse errors

---

go.mod
storage/mysql/mysql.go
storage/pgsql/postgresql.go

Hi folks.
I thought it would be a good idea to export the schema as a Go variable. Our ([fleet](https://github.com/fleetdm/fleet)) migration scripts are in Go so this change would come in handy.
And the embed feature was introduced in go 1.17 (hence the change in `go.mod` to upgrade). Am guessing this is a-ok as the related project, MicroMDM, is already in 1.17 ([go.mod](https://github.com/micromdm/micromdm/blob/main/go.mod)).

Export mysql schema variable (and bump go to 1.17)

---

.github/workflows/go.yml

Currently the MySQL backend is not tested, as it requires MySQL server
to run. I have added an integration test to the GitHub workflows which
starts MySQL server in a container, which allows the backend to be
tested. This ignores several "issues" that exist with the tests, such as
the fact that the test is non-idempotent, and fails to run twice.

add github action for mysql backend

---

storage/mysql/queue.go

NanoMDM allows for a single command to be queued for multiple devices. Since #48 landed, both queued commands and the command data itself is deleted after a device in finished with a command. However, I have observed deadlocks which occur when multiple devices trigger deletion for a shared command at once.
This can be avoided by placing a record lock on the command row before attempting a delete, so that only one device's enrollment queue can be cleared at a time.
This should have minimal impacts on performance as it will only serialize deletes to a single command. Furthermore, as the lock on the command record must be taken anyway, this does not add any additional locking to the transaction.
I have tested this, and have confirmed that it prevents deadlocks in NanoMDM. Furthermore, I have …

Prevent deadlock during command deletion in MySQL

---

storage/mysql/queue.go
storage/mysql/schema.00009.sql
storage/mysql/schema.sql

The view_queue is not materialized, and thus functions as syntactic
sugar for a complex query. Furthermore, our infrastructure works poorly
with views. Therefore, this usage adds a significant maintainership
burden for little gain.
This commit removes the view from NanoMDM code paths, but it still
exists in the schema. This is purely for convenience and interactive
users.
Furthermore, I added an index used by the queue query, which should have
existed for the view. This should improve performance.
Testing:
* Tested migration - see the schema migration script
* Tested base functionality
* Passes new integration test
depends on #58 
fixes #53 for mysql backend

remove view from mysql backend

---

service/request.go
storage/mysql/bstoken.go
storage/mysql/bstoken_test.go
storage/mysql/common_test.go
storage/mysql/device_test.go
storage/mysql/queue_test.go

This commit fixes an error when the bootstrap token for a device is NULL. Apple [specifies][0] the behaviour of `GetBootstrapToken` to return an empty body when there is no bootstrap token for the device. This behaviour has been conformed to.
[0]: https://developer.apple.com/documentation/devicemanagement/get_bootstrap_token

Fix error on MySQL backend when bsToken null

---

http/api/api.go

New `not_after` key:
```sh
$ cat push.pem push.key | curl -u nanomdm:$APIKEY -T - 'http://[::1]:9000/v1/pushcert'
{
"topic": "com.apple.mgmt.External.aaaa-bbbb-cccc-dddd-eeee",
"not_after": "2024-08-24T13:36:21Z"
}
```

return not_after (expiry) when uploading a pushcert

---

cmd/nanomdm/main.go
docs/operations-guide.md
http/authproxy/authproxy.go
http/http.go
http/mdm/mdm_cert.go
http/mdm/mdm_test.go
service/certauth/certauth.go
storage/all.go
storage/allmulti/certauth.go
storage/file/certauth.go
storage/mysql/certauth.go
storage/mysql/queue.go
storage/pgsql/certauth.go
storage/storage.go

Declarative Device Management has introduced the concept of an "MDM" Authentication style for asset URLs. For example:
https://github.com/apple/device-management/blob/b838baacf2e790db729b6ca3f52724adc8bfb96d/declarative/declarations/assets/credential.acme.yaml#L43-L57
So for content we want to protect this means we need to authenticate the MDM client identity certificate coming into the MDM server. However because file (or other content) serving is out of scope for NanoMDM we implement this as reverse proxy. When you specify the `-authproxy` switch on the command line with a URL (or use the relevant HTTP handlers in code) NanoMDM transparently authenticates the incoming HTTP request using MDM style authentication (in the same way we verify `CheckInURL` and `ServerURL` connections) then …

authproxy: MDM device identity authenticated HTTP requests

---

cmd/nanomdm/main.go
go.mod
push/buford/buford.go
push/nanopush/nanopush.go
push/nanopush/provider.go
push/nanopush/provider_test.go
push/push.go
push/service/service.go

The push library we've used forever, [buford](https://github.com/RobotsAndPencils/buford), was archived by the maintainers in early June of 2023. I quickly looked at a couple other libraries:
* https://github.com/sideshow/apns2 - a popular library. seem a bit large/kitchen-sink-ey, but not bad.
* https://github.com/edganiukov/apns - nice and tiny, but too app-focused (no custom payloads), not sure the correct non-JWT http2 forcing is done, either.
However, because our use of APNs for MDM purposes is limited in scope and we don't need the bells and whistles of an app-focused APNs library I took a stab at implementing just native HTTP/2 connections ourselves. There's not a whole lot of magic to make it work.
This PR plugs right into the `PushProvider` and `PushProviderFactory` interfaces …

new push provider: nanopush

---

cmd/nanomdm/main.go
docs/operations-guide.md
service/nanomdm/service.go
service/nanomdm/ua.go
service/nanomdm/ua_test.go
service/service.go
storage/storage.go

Also add tests and a CLI option to turn on "zero-length" `DigestChallenge` mode (`-ua-zl-dc`).
Per the updated Operations Guide docs:
> By default NanoMDM will response to the `UserAuthenticate` message with an HTTP 410 response effectively declining management of the MDM user. Enabling this option turns on the "zero-length" Digest Challenge mode where reply with an empty Digest Challenge to enable management each time a client enrolls. See also [Apple's discussion of UserAthenticate](https://developer.apple.com/documentation/devicemanagement/userauthenticate#discussion) for more information.

Split out UserAuthenticate

---

cmd/nanomdm/main.go
docs/operations-guide.md

Also add documentation to this effect for the `-dm` switch.

warn if a DDM url does not contain a trailing slash

---

cmd/nanomdm/main.go
docs/enroll.mobileconfig
mdm/checkin.go
mdm/checkin_test.go
service/certauth/helpers_test.go
service/certauth/service.go
service/dump/dump.go
service/microwebhook/service.go
service/multi/multi.go
service/nanomdm/service.go
service/nanomdm/token.go
service/nanomdm/token_test.go
service/request.go
service/service.go

Initial implementation of the *framing* for the `GetToken` check-in message.
**Note:** this is just the scaffolding to (eventually) support handling/handing-off of the GetToken check-in [`TokenServiceType`s](https://developer.apple.com/documentation/devicemanagement/gettokenrequest) of `com.apple.maid` and `com.apple.watch.pairing`.

GetToken check-in message framing

---

cmd/nanomdm/main.go
docs/operations-guide.md
http/mdm/cert_extract.go
http/mdm/cert_extract_test.go
http/mdm/mdm_cert.go

Per the updated operations guide:
> With the `-cert-header` switch you can specify the name of an HTTP header that is passed to NanoMDM to instead read the client identity certificate from. **The format of the header is parsed as RFC 9440 if it begins with a colon,** otherwise a URL query-escaped PEM certificate is assumed.
> 
> [RFC 9440](https://datatracker.ietf.org/doc/rfc9440/) specifies a Base-64 encoded DER certificate surrounded by colons. The URL query-escaped PEM certificate is ostensibly to support Nginx' [$ssl_client_escaped_cert](http://nginx.org/en/docs/http/ngx_http_ssl_module.html) in a [proxy_set_header](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_set_header) directive. Though any reverse proxy setting similar headers can be used, of course. Again the …

add support for rfc9440 cert headers

---

http/mdm/mdm.go
mdm/mdm.go
service/certauth/certauth.go
service/microwebhook/service.go
service/multi/context_test.go
service/multi/multi.go
service/nanomdm/dm.go
service/nanomdm/service.go
service/nanomdm/token_test.go
service/nanomdm/ua.go
storage/allmulti/allmulti.go
storage/allmulti/bstoken.go
storage/allmulti/certauth.go
storage/allmulti/queue.go
storage/kv/bstoken.go
storage/kv/certauth.go
storage/kv/kv.go
storage/kv/mdm.go
storage/kv/queue.go
storage/mysql/bstoken.go
storage/mysql/certauth.go
storage/mysql/mysql.go
storage/mysql/queue.go
storage/pgsql/bstoken.go
storage/pgsql/certauth.go
storage/pgsql/postgresql.go
storage/pgsql/queue.go
test/enrollment/enrollment.go

In line with the stdlib `http` package, make the direct `context.Context` in the MDM request immutable. This forces users to retrieve it via an accessor method (`Context()`) and requires cloning the MDM request object to change the context, leaving the previous request object context untouched. This is all in service of more predictable and safer code.

immutable context on mdm request
